---
- name: Create systemd service
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ project_name }}.service"
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start service
  systemd:
    name: "{{ project_name }}"
    enabled: yes
    state: started 