---
- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Allow UFW rules
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - ssh
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled