# Generated by Django 5.1.4 on 2025-01-13 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Add unique constraint after handling duplicates
            """
            UPDATE auth_user
            SET email = email || '_' || (
                SELECT COUNT(*)
                FROM auth_user AS t2
                WHERE t2.email = auth_user.email
                AND t2.id <= auth_user.id
            )
            WHERE email IN (
                SELECT email
                FROM auth_user
                GROUP BY email
                HAVING COUNT(*) > 1
            );

            CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_unique ON auth_user(email);
            """,
            # Reverse SQL - Remove unique constraint
            "DROP INDEX IF EXISTS auth_user_email_unique;",
        )
    ]
