# Generated by Django 5.1.4 on 2025-01-13 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Add unique constraint after removing duplicates
            """
            -- First, update duplicate emails to make them unique by appending a counter
            WITH duplicates AS (
                SELECT email, ROW_NUMBER() OVER (PARTITION BY email ORDER BY date_joined) as rn
                FROM auth_user
                WHERE email IN (
                    SELECT email
                    FROM auth_user
                    GROUP BY email
                    HAVING COUNT(*) > 1
                )
            )
            UPDATE auth_user
            SET email = CONCAT(email, '_', duplicates.rn)
            FROM duplicates
            WHERE auth_user.email = duplicates.email
            AND duplicates.rn > 1;

            -- Then add the unique constraint
            ALTER TABLE auth_user ADD CONSTRAINT auth_user_email_unique UNIQUE (email);
            """,
            # Reverse SQL - Remove unique constraint
            "ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS auth_user_email_unique;",
        )
    ]
