# Generated by Django 5.1.4 on 2025-01-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific session this payment is for, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="web.session",
            ),
        ),
    ]
