# Generated by Django 5.1.4 on 2025-01-13 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Add unique constraint after removing duplicates
            """
            -- First, update duplicate emails to make them unique by appending a counter
            UPDATE auth_user a
            JOIN (
                SELECT email, id,
                    @rn := IF(@prev = email, @rn + 1,
                        IF(@prev := email, 1, 1)) AS rn
                FROM auth_user, (SELECT @prev := NULL, @rn := 0) AS vars
                ORDER BY email, id
            ) AS duplicates ON a.id = duplicates.id
            SET a.email = CONCAT(a.email, '_', duplicates.rn)
            WHERE duplicates.rn > 1;

            -- Then add the unique constraint
            ALTER TABLE auth_user ADD CONSTRAINT auth_user_email_unique UNIQUE (email);
            """,
            # Reverse SQL - Remove unique constraint
            "ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS auth_user_email_unique;",
        )
    ]
