# Generated by Django 5.1.4 on 2025-01-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("programming", "Programming"),
                    ("design", "Design"),
                    ("business", "Business"),
                    ("marketing", "Marketing"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.CharField(blank=True, help_text="Comma-separated tags", max_length=200),
        ),
    ]
