# Generated by Django 5.1.4 on 2025-01-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_payment_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="enrollment",
            field=models.ForeignKey(
                help_text="The enrollment this payment is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="web.enrollment",
            ),
        ),
    ]
