# Generated by Django 5.1.4 on 2025-01-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_sessionenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
