# Generated by Django 5.1.4 on 2025-01-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_course_created_at_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
