# Generated by Django 5.1.4 on 2025-01-14 23:54

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_enrollment_payment_intent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_objectives",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
