# Generated by Django 5.1.4 on 2025-01-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="", blank=True, upload_to="avatars/"),
        ),
    ]
