# Generated by Django 5.1.4 on 2025-01-11 21:48

import django.db.models.deletion
from django.db import migrations, models


def create_initial_subjects(apps, schema_editor):
    Subject = apps.get_model("web", "Subject")

    # Create subjects from existing categories
    subject_mapping = {
        "programming": {
            "name": "Programming",
            "icon": "fas fa-code",
            "description": "Programming and software development courses",
            "slug": "programming",
        },
        "design": {
            "name": "Design",
            "icon": "fas fa-paint-brush",
            "description": "Graphic, web, and UI/UX design courses",
            "slug": "design",
        },
        "business": {
            "name": "Business",
            "icon": "fas fa-briefcase",
            "description": "Business, entrepreneurship, and management courses",
            "slug": "business",
        },
        "marketing": {
            "name": "Marketing",
            "icon": "fas fa-bullhorn",
            "description": "Digital marketing and advertising courses",
            "slug": "marketing",
        },
        "other": {
            "name": "Other",
            "icon": "fas fa-dot-circle",
            "description": "Other educational courses",
            "slug": "other",
        },
    }

    # Create subjects and store mapping
    created_subjects = {}
    for key, data in subject_mapping.items():
        subject = Subject.objects.create(**data)
        created_subjects[key] = subject


def reverse_subject_migration(apps, schema_editor):
    Subject = apps.get_model("web", "Subject")
    Subject.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Font Awesome icon class", max_length=50),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="web.subject",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(create_initial_subjects, reverse_subject_migration),
    ]
