# Generated by Django 5.1.4 on 2025-01-12 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_add_allow_individual_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_user_or_session_key",
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                check=models.Q(("user__isnull", False)) | models.Q(("session_key__gt", "")),
                name="cart_user_or_session_key",
            ),
        ),
    ]
