# Generated by Django 5.1.4 on 2025-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10.0,
                help_text="Commission rate in percentage (e.g., 10.00 for 10%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_account_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
