# Generated by Django 5.1.4 on 2025-01-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_blogpost_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Course image (300x150 pixels)",
                upload_to="course_images/%Y/%m/%d/",
            ),
        ),
    ]
