# Generated by Django 5.1.4 on 2025-01-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_profile_commission_rate_profile_stripe_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="invite_only",
            field=models.BooleanField(
                default=False, help_text="If enabled, students can only enroll with an invitation"
            ),
        ),
    ]
