# Generated by Django 5.1.4 on 2025-01-23 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_course_invite_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="external_url",
            field=models.URLField(blank=True, help_text="URL for external content like YouTube videos"),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="requires_enrollment",
            field=models.BooleanField(
                default=True, help_text="If True, only enrolled students can access full content"
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="file",
            field=models.FileField(blank=True, upload_to="course_materials/"),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("image", "Image"),
                    ("document", "Document"),
                    ("presentation", "Presentation"),
                    ("exercise", "Exercise"),
                    ("quiz", "Quiz"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventCalendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("share_token", models.CharField(max_length=32, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("day", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_slots", to="web.eventcalendar"
                    ),
                ),
            ],
            options={
                "unique_together": {("calendar", "name", "day")},
            },
        ),
    ]
