# Generated by Django 5.1.4 on 2025-01-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_searchlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(blank=True, default="", max_length=100)),
                ("user", models.CharField(blank=True, default="", max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("agent", models.TextField(blank=True, default="")),
                ("count", models.BigIntegerField(default=1)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("referer", models.CharField(blank=True, default="", max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_requests",
                        to="web.course",
                    ),
                ),
            ],
        ),
    ]
