# Generated by Django 5.1.4 on 2025-02-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_webrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="enable_rollover",
            field=models.BooleanField(
                default=False, help_text="Enable automatic date rollover if no students are enrolled"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="is_rolled_over",
            field=models.BooleanField(default=False, help_text="Whether this session has been rolled over"),
        ),
        migrations.AddField(
            model_name="session",
            name="original_end_time",
            field=models.DateTimeField(blank=True, help_text="Original end time before any rollovers", null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="original_start_time",
            field=models.DateTimeField(blank=True, help_text="Original start time before any rollovers", null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="rollover_pattern",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                default="weekly",
                help_text="How often to roll over the session dates",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="teacher_confirmed",
            field=models.BooleanField(
                default=False, help_text="Whether the teacher has confirmed the rolled over dates"
            ),
        ),
    ]
