# Generated by Django 5.1.5 on 2025-02-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_session_enable_rollover_session_is_rolled_over_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('document', 'Document'), ('presentation', 'Presentation'), ('exercise', 'Exercise'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('other', 'Other')], max_length=20),
        ),
    ]
