# Generated by Django 5.1.4 on 2025-02-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_session_enable_rollover_session_is_rolled_over_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="referral_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="web.profile",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Course image (will be resized to 300x300 pixels)", upload_to="course_images"
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("image", "Image"),
                    ("document", "Document"),
                    ("presentation", "Presentation"),
                    ("exercise", "Exercise"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, default="", upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="expertise",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
