# Generated by Django 5.1.5 on 2025-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_coursematerial_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='web/static/images/default-course.jpg', help_text='Course image (will be resized to 300x150 pixels)', upload_to='course_images'),
        ),
    ]
