# Generated by Django 5.1.5 on 2025-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course image (will be resized to 300x300 pixels)', upload_to='course_images'),
        ),
    ]
