# Generated by Django 5.1.5 on 2025-02-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_convert_blogpost_content_to_markdownx"),
        ("web", "0019_update_charset_to_utf8mb4"),
    ]

    operations = []
