# Generated by Django 5.1.6 on 2025-03-07 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_challenge_challengesubmission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Product title (e.g., 'Algebra Basics Workbook')", max_length=100)),
                ("description", models.TextField(help_text="Detailed product description")),
                ("price", models.DecimalField(decimal_places=2, help_text="Price in USD", max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Discounted price (optional)", max_digits=10, null=True
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(blank=True, help_text="Leave blank for digital products", null=True),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("physical", "Physical Product"), ("digital", "Digital Download")],
                        default="physical",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, help_text="Required for digital products", upload_to="digital_goods/"),
                ),
                (
                    "category",
                    models.CharField(blank=True, help_text="e.g., 'Books', 'Course Materials'", max_length=100),
                ),
                ("is_available", models.BooleanField(default=True, help_text="Show/hide product from store")),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Inventory tracking ID (auto-generated)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "course"), ("cart", "session")},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="goods",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="web.goods",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "course"), ("cart", "goods"), ("cart", "session")},
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(help_text="Product display image", upload_to="goods_images/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Accessibility description for screen readers", max_length=125
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goods_images", to="web.goods"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goods",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="goods_images", to="web.productimage"),
        ),
        migrations.CreateModel(
            name="Storefront",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        default="Default Store Name",
                        help_text="Display name for your store",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Describe your store for customers")),
                (
                    "logo",
                    models.ImageField(blank=True, help_text="Recommended size: 200x200px", upload_to="store_logos/"),
                ),
                (
                    "store_slug",
                    models.SlugField(blank=True, help_text="Auto-generated URL-friendly identifier", unique=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Enable/disable public visibility of your store"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher Profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_price", models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Payment"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("shipping_address", models.JSONField(blank=True, help_text="Structured shipping details", null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("terms_accepted", models.BooleanField(default=False, help_text="User accepted terms during checkout")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "storefront",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="web.storefront",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goods",
            name="storefront",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="web.storefront"
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_at_purchase", models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                (
                    "discounted_price_at_purchase",
                    models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.goods", verbose_name="Product"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="web.order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Line Item",
                "unique_together": {("order", "goods")},
            },
        ),
    ]
