# Generated by Django 5.1.6 on 2025-03-13 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_goods_alter_cartitem_unique_together_cartitem_goods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='URL for external content like YouTube videos')),
                ('category', models.CharField(choices=[('science', 'Science'), ('technology', 'Technology'), ('mathematics', 'Mathematics'), ('programming', 'Programming'), ('arts', 'Arts'), ('language', 'Language Learning'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Educational Video',
                'verbose_name_plural': 'Educational Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
