# Generated by Django 5.1.6 on 2025-03-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_meme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="caption",
            field=models.TextField(help_text="The text content of the meme"),
        ),
        migrations.AlterField(
            model_name="meme",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memes", to="web.subject"
            ),
        ),
        migrations.AlterField(
            model_name="meme",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
