# Generated by Django 5.1.6 on 2025-03-15 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_add_team_collaboration_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamgoalmember",
            old_name="completion_date",
            new_name="completed_at",
        ),
        migrations.RenameField(
            model_name="teamgoalmember",
            old_name="goal",
            new_name="team_goal",
        ),
        migrations.AlterUniqueTogether(
            name="teamgoalmember",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="teamgoal",
            name="target_date",
        ),
        migrations.AddField(
            model_name="teamgoal",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamgoalmember",
            name="role",
            field=models.CharField(
                choices=[("leader", "Team Leader"), ("member", "Team Member")], default="member", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="teamgoal",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("completed", "Completed"), ("cancelled", "Cancelled")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teamgoalmember",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sent_invites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamgoalmember",
            unique_together={("team_goal", "user")},
        ),
    ]
