# Generated by Django 5.1.6 on 2025-03-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_progresstracker"),
        ("web", "0024_create_success_story"),
    ]

    operations = []
