# Generated by Django 5.1.6 on 2025-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_create_success_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="successstory",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("archived", "Archived")], default="published", max_length=10
            ),
        ),
    ]
