# Generated by Django 5.1.6 on 2025-03-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_meme_caption_alter_meme_subject_and_more"),
        ("web", "0024_create_success_story"),
    ]

    operations = []
