# Generated by Django 5.1.6 on 2025-03-18 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_create_success_story"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressTracker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("current_value", models.IntegerField(default=0)),
                ("target_value", models.IntegerField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue-600", "Primary"),
                            ("green-600", "Success"),
                            ("yellow-600", "Warning"),
                            ("red-600", "Danger"),
                            ("gray-600", "Secondary"),
                        ],
                        default="blue-600",
                        max_length=20,
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("embed_code", models.CharField(editable=False, max_length=36, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_trackers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
