# Generated by Django 5.1.6 on 2025-03-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_donation"),
        ("web", "0025_alter_successstory_status"),
    ]

    operations = []
