# Generated by Django 5.1.6 on 2025-03-18 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_progresstracker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="A descriptive title for the meme", max_length=200)),
                ("caption", models.TextField(blank=True, help_text="The text content of the meme")),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a meme image (JPG, PNG, or GIF, max 2MB)",
                        upload_to="memes/",
                        validators=[web.models.validate_image_size, web.models.validate_image_extension],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The educational subject this meme relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memes",
                        to="web.subject",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meme",
                "verbose_name_plural": "Memes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="web_meme_created_b43882_idx"),
                    models.Index(fields=["subject"], name="web_meme_subject_1b89ce_idx"),
                ],
            },
        ),
    ]
