# Generated by Django 5.1.6 on 2025-03-18 12:44

from django.db import migrations
from django.utils.text import slugify


def update_subjects(apps, schema_editor):
    Subject = apps.get_model("web", "Subject")
    
    # Remove old hardcoded subjects if they exist
    old_subjects = ["Science", "Technology", "Mathematics", "Programming", "Arts", "Language", "Other"]
    Subject.objects.filter(name__in=old_subjects).delete()
    
    # Create new subjects from subjects.html
    new_subjects = [
        "Chemistry", "Mathematics", "Programming", "Psychology", 
        "Electronics", "Geography", "Literature", "Music Theory", 
        "Robotics", "Health & Wellness"
    ]
    
    for i, subject in enumerate(new_subjects):
        Subject.objects.get_or_create(
            name=subject,
            defaults={
                "slug": slugify(subject),
                "description": f"Learn about {subject}",
                "order": i,  # Set order based on list position
            },
        )

def reverse_update(apps, schema_editor):
    # Reverse migration if needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_educationalvideo'),
    ]

    operations = [
        migrations.RunPython(update_subjects, reverse_update),
    ]
