# Generated by Django 5.1.6 on 2025-03-13 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_subjects_from_categories(apps, schema_editor):
    """
    This function is no longer needed as we'll use existing subjects instead of
    creating hardcoded ones. We'll keep it empty to maintain migration history.
    """
    pass


def reverse_subject_creation(apps, schema_editor):
    """
    Since we're not creating any subjects in the forward migration,
    we don't need to delete anything in the reverse migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_enhance_meme_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_subjects_from_categories, reverse_code=reverse_subject_creation),
        migrations.CreateModel(
            name="EducationalVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("video_url", models.URLField(help_text="URL for external content like YouTube videos")),
                (
                    "category",
                    models.ForeignKey(
                        "web.Subject", on_delete=django.db.models.deletion.PROTECT, related_name="educational_videos"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educational_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Educational Video",
                "verbose_name_plural": "Educational Videos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
