# Generated by Django 5.1.6 on 2025-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_eyes",
            field=models.CharField(
                choices=[("round", "Round"), ("almond", "Almond"), ("narrow", "Narrow")], default="round", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_hair",
            field=models.CharField(
                choices=[("short", "Short"), ("long", "Long"), ("curly", "Curly"), ("bald", "Bald")],
                default="short",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_hair_color",
            field=models.CharField(
                choices=[("black", "Black"), ("brown", "Brown"), ("blonde", "Blonde"), ("red", "Red")],
                default="black",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_skin_tone",
            field=models.CharField(
                choices=[("light", "Light"), ("medium", "Medium"), ("dark", "Dark")], default="medium", max_length=20
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_eyes",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_hair",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_hair_color",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_skin_tone",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_background",
            field=models.CharField(
                choices=[
                    ("b6e3f4", "Light Blue"),
                    ("c0aede", "Lavender"),
                    ("d1d4f9", "Periwinkle"),
                    ("ffd5dc", "Pink"),
                    ("ffdfbf", "Peach"),
                    ("d1f4d9", "Mint"),
                    ("f9f9f9", "Light Gray"),
                ],
                default="f9f9f9",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_seed",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_style",
            field=models.CharField(
                choices=[
                    ("adventurer", "Adventurer"),
                    ("adventurer-neutral", "Adventurer Neutral"),
                    ("avataaars", "Avataaars"),
                    ("big-ears", "Big Ears"),
                    ("big-smile", "Big Smile"),
                    ("bottts", "Bottts"),
                    ("croodles", "Croodles"),
                    ("fun-emoji", "Fun Emoji"),
                    ("micah", "Micah"),
                    ("miniavs", "Mini Avatars"),
                    ("open-peeps", "Open Peeps"),
                    ("pixel-art", "Pixel Art"),
                ],
                default="avataaars",
                max_length=30,
            ),
        ),
    ]
