# Generated by Django 5.1.6 on 2025-03-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_learningstreak"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("private", "Private")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "share_code",
                    models.CharField(
                        blank=True, help_text="Unique code for sharing the quiz", max_length=8, null=True, unique=True
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=False, help_text="If enabled, users don't need to log in to take this quiz"
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(default=False, help_text="Show correct answers after quiz completion"),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(default=False, help_text="Randomize the order of questions"),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(blank=True, help_text="Time limit in minutes (optional)", null=True),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of attempts allowed (leave blank for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(default=70, help_text="Minimum percentage required to pass the quiz"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="quizzes", to="web.subject"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short", "Short Answer"),
                        ],
                        default="multiple",
                        max_length=10,
                    ),
                ),
                ("explanation", models.TextField(blank=True, help_text="Explanation of the correct answer")),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                ("image", models.ImageField(blank=True, default="", upload_to="quiz_questions/")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="web.quiz"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="web.quizquestion"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserQuiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "anonymous_id",
                    models.CharField(
                        blank=True, help_text="Identifier for non-logged-in users", max_length=36, default=""
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("max_score", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "answers",
                    models.JSONField(
                        blank=True, default=dict, help_text="JSON storing the user's answers and question IDs"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_quizzes", to="web.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User quiz attempts",
                "ordering": ["-start_time"],
            },
        ),
    ]
