# Generated by Django 5.1.6 on 2025-03-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_quiz_quizquestion_quizoption_userquiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="badge_icon",
            field=models.CharField(
                blank=True, help_text="Icon class for the badge (e.g., 'fas fa-trophy')", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="criteria_threshold",
            field=models.PositiveIntegerField(
                blank=True, help_text="Optional threshold required to earn this badge", null=True
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="achievement_type",
            field=models.CharField(
                choices=[
                    ("attendance", "Perfect Attendance"),
                    ("completion", "Course Completion"),
                    ("participation", "Active Participation"),
                    ("excellence", "Academic Excellence"),
                    ("quiz", "High Quiz Score"),
                    ("streak", "Daily Learning Streak"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="web.course",
            ),
        ),
    ]
