# Generated by Django 5.1.6 on 2025-03-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_waitingroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitingroom",
            name="fulfilled_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_waiting_rooms",
                to="web.course",
            ),
        ),
    ]
