# Generated by Django 5.1.6 on 2025-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0033_gradeablelink_linkgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_profile_public",
            field=models.BooleanField(
                default=False, help_text="Toggle to make your profile public so your details and stats are visible."
            ),
        ),
    ]
