# Generated by Django 5.1.6 on 2025-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_remove_profile_avatar_accessories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_expression',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_accessory',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_clothing',
            field=models.CharField(default='shirt', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_clothing_color',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_eyebrows',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_eyes',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_facial_hair',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_hair_color',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_mouth',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_nose',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_skin_color',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_top',
            field=models.CharField(default='short_hair', max_length=50),
        ),
    ]
