# Generated by Django 5.1.6 on 2025-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_remove_profile_avatar_expression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_clothing',
            field=models.CharField(default='hoodie', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_clothing_color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_eyebrows',
            field=models.CharField(default='raised', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_eyes',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_hair_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_mouth',
            field=models.CharField(default='smile', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_nose',
            field=models.CharField(default='round', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_top',
            field=models.CharField(default='short_waved', max_length=50),
        ),
    ]
