# Generated by Django 5.1.6 on 2025-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_peerchallenge_peerchallengeinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="how_did_you_hear_about_us",
            field=models.TextField(blank=True, help_text="How did you hear about us? You can enter text or a link."),
        ),
    ]
