# Generated by Django 5.1.6 on 2025-03-23 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_profile_how_did_you_hear_about_us"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="due_date",
            field=models.DateTimeField(blank=True, help_text="Deadline for assignment submission", null=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="final_reminder_sent",
            field=models.BooleanField(default=False, help_text="Whether a final reminder has been sent"),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="reminder_sent",
            field=models.BooleanField(default=False, help_text="Whether an early reminder has been sent"),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reminder_days_before",
                    models.IntegerField(default=3, help_text="Days before deadline to send first reminder"),
                ),
                (
                    "reminder_hours_before",
                    models.IntegerField(default=24, help_text="Hours before deadline to send final reminder"),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
