# Generated by Django 5.1.6 on 2025-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_coursematerial_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_accessories",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_background_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_clothes",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_clothes_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_eyebrows",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_eyes",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_facial_hair",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_facial_hair_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_hair_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_hair_style",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_mouth",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_skin",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_style",
            field=models.CharField(default="circle", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_svg",
            field=models.TextField(blank=True, help_text="Stored SVG string of the custom avatar"),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_accessories",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_clothes",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_clothes_color",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_eyebrows",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_eyes",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_facial_hair",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_facial_hair_color",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_hair_color",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_hair_style",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_mouth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_skin",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_expression",
            field=models.CharField(default="neutral", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_background_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_expression",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_accessory",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_clothing",
            field=models.CharField(default="shirt", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_clothing_color",
            field=models.CharField(default="blue", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_eyebrows",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_eyes",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_facial_hair",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_hair_color",
            field=models.CharField(default="black", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_mouth",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_nose",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_skin_color",
            field=models.CharField(default="light", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_top",
            field=models.CharField(default="short_hair", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_clothing",
            field=models.CharField(default="hoodie", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_clothing_color",
            field=models.CharField(default="#0000FF", max_length=7),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_eyebrows",
            field=models.CharField(default="raised", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_eyes",
            field=models.CharField(default="normal", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_hair_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_mouth",
            field=models.CharField(default="smile", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_nose",
            field=models.CharField(default="round", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_top",
            field=models.CharField(default="short_waved", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_eyebrows",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_eyes",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_mouth",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_nose",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_top",
            field=models.CharField(default="short_flat", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, default="", upload_to="avatars"),
        ),
    ]
