# Generated by Django 5.1.6 on 2025-03-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_waitingroom_fulfilled_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitingroom",
            options={},
        ),
    ]
