# Generated by Django 5.1.6 on 2025-03-24 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0039_notehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challengesubmission",
            name="points_awarded",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="donation",
            name="award_points",
            field=models.BooleanField(default=True, help_text="Award points to user for donation"),
        ),
        migrations.AddField(
            model_name="donation",
            name="points_multiplier",
            field=models.DecimalField(
                decimal_places=2, default=1.0, help_text="Points per dollar multiplier", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="is_reward",
            field=models.BooleanField(default=False, help_text="Can be unlocked as achievement reward"),
        ),
        migrations.AddField(
            model_name="goods",
            name="points_required",
            field=models.PositiveIntegerField(blank=True, help_text="Points needed to unlock this reward", null=True),
        ),
        migrations.AlterUniqueTogether(
            name="challengesubmission",
            unique_together={("user", "challenge")},
        ),
        migrations.CreateModel(
            name="Points",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(help_text="Reason for awarding points", max_length=255)),
                (
                    "point_type",
                    models.CharField(
                        choices=[("regular", "Regular Points"), ("streak", "Streak Points"), ("bonus", "Bonus Points")],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("current_streak", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_awarded",
                        to="web.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="points", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Points",
                "indexes": [
                    models.Index(fields=["user", "awarded_at"], name="web_points_user_id_3acb2a_idx"),
                    models.Index(fields=["awarded_at"], name="web_points_awarded_c490d6_idx"),
                ],
            },
        ),
    ]
