# Generated by Django 5.1.6 on 2025-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0040_challengesubmission_points_awarded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[("weekly", "Weekly Challenge"), ("one_time", "One-time Challenge")],
                default="weekly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="week_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("challenge_type", "weekly")),
                fields=("week_number",),
                name="unique_week_number_for_weekly_challenges",
            ),
        ),
    ]
