# Generated by Django 5.1.6 on 2025-03-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0043_waitingroom_fulfilled_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitingroom",
            options={},
        ),
    ]
