# Generated by Django 5.1.6 on 2025-03-25 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0045_add_membership_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature_id", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("vote", models.CharField(choices=[("up", "Thumbs Up"), ("down", "Thumbs Down")], max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Vote",
                "verbose_name_plural": "Feature Votes",
                "indexes": [
                    models.Index(fields=["feature_id", "user"], name="web_feature_feature_9fbd0b_idx"),
                    models.Index(fields=["feature_id", "ip_address"], name="web_feature_feature_988c48_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["feature_id", "user"],
                        name="unique_user_feature_vote",
                        condition=models.Q(user__isnull=False),
                    ),
                    models.UniqueConstraint(
                        fields=["feature_id", "ip_address"],
                        name="unique_ip_feature_vote",
                        condition=models.Q(ip_address__isnull=False),
                    ),
                ],
            },
        ),
    ]
