# Generated by Django 5.1.6 on 2025-03-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_add_laptop_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualseat',
            name='laptop_open',
        ),
    ]
