# Generated by Django 5.1.6 on 2025-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_remove_virtualseat_laptop_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualseat',
            name='laptop_open',
            field=models.BooleanField(default=False),
        ),
    ]
