# Generated by Django 5.1.6 on 2025-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0052_add_meme_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="featured",
            field=models.BooleanField(default=False, help_text="Mark this product as featured"),
        ),
    ]
