# Generated by Django 5.1.6 on 2025-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0058_forumtopic_github_issue_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalvideo",
            name="description",
            field=models.TextField(blank=True, help_text="Optional – describe what viewers will learn from this video"),
        ),
    ]
