# Generated by Django 5.1.6 on 2025-05-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_alter_educationalvideo_description_videorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Optional classroom session identifier', max_length=100, null=True)),
                ('position_x', models.FloatField(default=400, help_text="Player's X position in the classroom")),
                ('position_y', models.FloatField(default=300, help_text="Player's Y position in the classroom")),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the state was updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChairOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_id', models.CharField(help_text='Unique identifier for the chair', max_length=50)),
                ('session_id', models.CharField(blank=True, help_text='Optional classroom session identifier', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_chairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chair_id', 'session_id')},
            },
        ),
    ]
