# Generated by Django 5.1.6 on 2025-06-04 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_alter_educationalvideo_description_videorequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualClassroom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_students", models.PositiveIntegerField(default=30)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_classrooms",
                        to="web.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualClassroomCustomization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wall_color", models.CharField(default="#E6E2D7", max_length=7)),
                ("floor_color", models.CharField(default="#C7B299", max_length=7)),
                ("desk_color", models.CharField(default="#8B4513", max_length=7)),
                ("chair_color", models.CharField(default="#4B0082", max_length=7)),
                ("board_color", models.CharField(default="#005C53", max_length=7)),
                ("number_of_rows", models.PositiveIntegerField(default=5)),
                ("desks_per_row", models.PositiveIntegerField(default=6)),
                ("has_plants", models.BooleanField(default=True)),
                ("has_windows", models.BooleanField(default=True)),
                ("has_bookshelf", models.BooleanField(default=True)),
                ("has_clock", models.BooleanField(default=True)),
                ("has_carpet", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization_settings",
                        to="web.virtualclassroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Classroom Customization",
                "verbose_name_plural": "Virtual Classroom Customizations",
            },
        ),
        migrations.CreateModel(
            name="VirtualClassroomWhiteboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("canvas_data", models.JSONField(blank=True, default=dict)),
                ("background_image", models.TextField(blank=True, default="")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "classroom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard",
                        to="web.virtualclassroom",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Classroom Whiteboard",
                "verbose_name_plural": "Virtual Classroom Whiteboards",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="VirtualClassroomParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("seat_id", models.CharField(blank=True, default="", max_length=20)),
                (
                    "classroom",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.virtualclassroom"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("classroom", "user")},
            },
        ),
    ]
