# Generated by Django 5.1.6 on 2025-10-05 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_alter_educationalvideo_description_videorequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitingroom",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="waitingroom",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="For waiting for next session of an existing course",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_waiting_rooms",
                to="web.course",
            ),
        ),
        migrations.AlterField(
            model_name="waitingroom",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_waiting_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="waitingroom",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="waitingroom",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="waitingroom",
            name="topics",
            field=models.TextField(blank=True, help_text="Comma-separated list of topics"),
        ),
    ]
