# Generated by Django 5.1.6 on 2025-05-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_virtualclassroom_virtualclassroomcustomization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualclassroom',
            name='customization',
        ),
        migrations.AlterField(
            model_name='virtualclassroomcustomization',
            name='board_color',
            field=models.CharField(default='#005C53', max_length=7),
        ),
        migrations.AlterField(
            model_name='virtualclassroomcustomization',
            name='floor_color',
            field=models.CharField(default='#C7B299', max_length=7),
        ),
        migrations.AlterField(
            model_name='virtualclassroomcustomization',
            name='wall_color',
            field=models.CharField(default='#E6E2D7', max_length=7),
        ),
    ]
