# Generated by Django 5.1.6 on 2025-05-31 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_virtualclassroomparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualclassroomparticipant',
            options={},
        ),
        migrations.RemoveField(
            model_name='virtualclassroomparticipant',
            name='last_active',
        ),
        migrations.AlterField(
            model_name='virtualclassroomparticipant',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.virtualclassroom'),
        ),
        migrations.AlterField(
            model_name='virtualclassroomparticipant',
            name='seat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='virtualclassroomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
