# Generated by Django 5.1.6 on 2025-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_virtualclassroomparticipant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualclassroomparticipant',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
