# Generated by Django 5.1.6 on 2025-05-31 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_virtualclassroomparticipant_last_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualClassroomWhiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_data', models.JSONField(default=dict, help_text='Canvas drawing data in JSON format')),
                ('background_image', models.TextField(blank=True, help_text='Base64 encoded background image', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard', to='web.virtualclassroom')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtual Classroom Whiteboard',
                'verbose_name_plural': 'Virtual Classroom Whiteboards',
            },
        ),
    ]
