# Generated by Django 5.1.6 on 2025-05-31 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_virtualclassroomwhiteboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualclassroomwhiteboard',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Virtual Classroom Whiteboard', 'verbose_name_plural': 'Virtual Classroom Whiteboards'},
        ),
        migrations.AddField(
            model_name='virtualclassroomwhiteboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='virtualclassroomwhiteboard',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualclassroomwhiteboard',
            name='canvas_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
