# Generated by Django 5.1.6 on 2025-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_alter_virtualclassroomwhiteboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualclassroomwhiteboard',
            name='canvas_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
